spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/${spring.application.name}
    username: sa
    password:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
      preferredNetworks:
        - 172.16.100

eureka:
  client:
#    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    refresh:
      enable: false
    disable-delta: true
    prefer-ip-address: true
  instance:
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
