server:
  port: 8088

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    bus:
      enabled: true
    config:
      server:
        composite:
          - type: native
            search-locations: classpath:/config
        prefix: config

management:
  endpoints:
    web:
      exposure:
        include: '*'
